env: standard
runtime: nodejs14
service: default

handlers:
  - url: /static
    static_dir: static

  - url: /(.*\.(json|ico|js|png))$
    static_files: static/\1
    upload: static/.*\.(json|ico|js|png)$

  - url: .*
    static_files: static/index.html
    upload: static/index.html
    secure: always
    redirect_http_response_code: 301