env: standard
runtime: nodejs14
service: usuarios

instance_class: B1

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

basic_scaling:
  max_instances: 1
  idle_timeout: 10m

env_variables:
  NODE_ENV: 'production'

network:
  session_affinity: true